#!/usr/bin/env bash
set -e

usage() {
  echo "Usage: $0 [ -t INSTANCE_TYPE ] URL"
  exit 2
}

set_variable() {
  local varname=$1
  shift
  if [ -z "${!varname}" ]; then
    eval "$varname=\"$@\""
  else
    echo "Error: $varname already set"
    usage
  fi
}

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
CSS_FILE="$ROOT_DIR/css/missing-instances.css"

unset INSTANCE_URL INSTANCE_TYPE

while getopts 't:?h' c; do
  case $c in
  t) set_variable INSTANCE_TYPE $OPTARG ;;
  h | ?)
    echo $@
    usage
    ;;
  esac
done

shift $((OPTIND - 1))
INSTANCE_URL=$@
INSTANCE_NAME=$INSTANCE_URL

res="${INSTANCE_NAME//[^.]/}"
if [ ${#res} -gt 1 ]; then
  case $INSTANCE_NAME in
  social*) INSTANCE_NAME=".${INSTANCE_NAME#"social"}" ;;
  soc*) INSTANCE_NAME=".${INSTANCE_NAME#"soc"}" ;;
  mastodon*) INSTANCE_NAME=".${INSTANCE_NAME#"mastodon"}" ;;
  mas*) INSTANCE_NAME=".${INSTANCE_NAME#"mas"}" ;;
  pleroma*) INSTANCE_NAME=".${INSTANCE_NAME#"pleroma"}" ;;
  misskey*) INSTANCE_NAME=".${INSTANCE_NAME#"misskey"}" ;;
  fedi*) INSTANCE_NAME=".${INSTANCE_NAME#"fedi"}" ;;
  akkoma*) INSTANCE_NAME=".${INSTANCE_NAME#"akkoma"}" ;;
  gts*) INSTANCE_NAME=".${INSTANCE_NAME#"gts"}" ;;
  toots*) INSTANCE_NAME=".${INSTANCE_NAME#"toots"}" ;;
  posts*) INSTANCE_NAME=".${INSTANCE_NAME#"posts"}" ;;
  esac
fi

MASTODON_TEMPLATE=".status a[href^='https://${INSTANCE_URL}'] .display-name::after{ padding:0 0 0 17px!important;height:var(--fh); font:var(--ff); background:var(--2),linear-gradient(90deg,#46a 64%,transparent); text-shadow:#46a 1px 1px,#46a -1px 1px,#46a 1px -1px,#46a -1px -1px;color:#fff!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fb);} .status__display-name[href^='https://${INSTANCE_URL}/'].muted::before, .notification__display-name[href^='https://${INSTANCE_URL}/']::before{ padding:0 18px 0 17px!important;vertical-align:var(--fv);height:var(--fh);line-height:var(--fl); font:var(--ff); background:var(--2),linear-gradient(90deg,#46a 64%,transparent); text-shadow:#46a 1px 1px,#46a -1px 1px,#46a 1px -1px,#46a -1px -1px;color:#fff!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fi);opacity:var(--fa);}"
PLEROMA_TEMPLATE=".status a[href^='https://${INSTANCE_URL}/'] .display-name::after{ padding:0 0 0 17px!important;height:var(--fh); font:var(--ff); background:var(--3),linear-gradient(90deg,#333 64%,transparent); text-shadow:#333 1px 1px,#333 -1px 1px,#333 1px -1px,#333 -1px -1px;color:#da5!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fb);} .status__display-name[href^='https://${INSTANCE_URL}/'].muted::before, .notification__display-name[href^='https://${INSTANCE_URL}/']::before{ padding:0 18px 0 17px!important;vertical-align:var(--fv);height:var(--fh);line-height:var(--fl); font:var(--ff); background:var(--3),linear-gradient(90deg,#333 64%,transparent); text-shadow:#333 1px 1px,#333 -1px 1px,#333 1px -1px,#333 -1px -1px;color:#da5!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fi);opacity:var(--fa);}"
GTS_TEMPLATE=".status a[href^='https://${INSTANCE_URL}/'] .display-name::after{ padding:0 0 0 17px!important;height:var(--fh); font:var(--ff); background:var(--gts),linear-gradient(90deg,#b85922 64%,transparent); text-shadow:#b85922 1px 1px,#b85922 -1px 1px,#b85922 1px -1px,#b85922 -1px -1px;color:#fff!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fb);} .status__display-name[href^='https://${INSTANCE_URL}/'].muted::before, .notification__display-name[href^='https://${INSTANCE_URL}/']::before{ padding:0 18px 0 17px!important;vertical-align:var(--fv);height:var(--fh);line-height:var(--fl); font:var(--ff); background:var(--gts),linear-gradient(90deg,#b85922 64%,transparent); text-shadow:#b85922 1px 1px,#b85922 -1px 1px,#b85922 1px -1px,#b85922 -1px -1px;color:#fff!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fi);opacity:var(--fa);}"
FRIENDICA_TEMPLATE=".status a[href^='https://${INSTANCE_URL}/'] .display-name::after{ padding:0 0 0 17px!important;height:var(--fh); font:var(--ff); background:var(--f),linear-gradient(90deg,#17a 64%,transparent); text-shadow:#17a 1px 1px,#17a -1px 1px,#17a 1px -1px,#17a -1px -1px;color:#fc2!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fb);} .status__display-name[href^='https://${INSTANCE_URL}/'].muted::before, .notification__display-name[href^='https://${INSTANCE_URL}/']::before{ padding:0 18px 0 17px!important;vertical-align:var(--fv);height:var(--fh);line-height:var(--fl); font:var(--ff); background:var(--f),linear-gradient(90deg,#17a 64%,transparent); text-shadow:#17a 1px 1px,#17a -1px 1px,#17a 1px -1px,#17a -1px -1px;color:#fc2!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fi);opacity:var(--fa);}"
MISSKEY_TEMPLATE=".status a[href^='https://${INSTANCE_URL}/'] .display-name::after{ padding:0 0 0 17px!important;height:var(--fh); font:var(--ff); background:var(--4),linear-gradient(90deg,#332 64%,transparent); text-shadow:#333 1px 1px,#333 -1px 1px,#333 1px -1px,#333 -1px -1px;color:#9c0!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fb);} .status__display-name[href^='https://${INSTANCE_URL}/'].muted::before, .notification__display-name[href^='https://${INSTANCE_URL}/']::before{ padding:0 18px 0 17px!important;vertical-align:var(--fv);height:var(--fh);line-height:var(--fl); font:var(--ff); background:var(--4),linear-gradient(90deg,#332 64%,transparent); text-shadow:#333 1px 1px,#333 -1px 1px,#333 1px -1px,#333 -1px -1px;color:#9c0!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fi);opacity:var(--fa);}"
AKKOMA_TEMPLATE=".status a[href^='https://${INSTANCE_URL}/'] .display-name::after{ padding:0 0 0 17px!important;height:var(--fh); font:var(--ff); background:var(--cit1),linear-gradient(90deg,#3a2a37 64%,transparent); text-shadow:#3a2a37 1px 1px,#3a2a37 -1px 1px,#3a2a37 1px -1px,#3a2a37 -1px -1px;color:#a97189!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fb);} .status__display-name[href^='https://${INSTANCE_URL}/'].muted::before, .notification__display-name[href^='https://${INSTANCE_URL}/']::before{ padding:0 18px 0 17px!important;vertical-align:var(--fv);height:var(--fh);line-height:var(--fl); font:var(--ff); background:var(--cit1),linear-gradient(90deg,#3a2a37 64%,transparent); text-shadow:#3a2a37 1px 1px,#3a2a37 -1px 1px,#3a2a37 1px -1px,#3a2a37 -1px -1px;color:#a97189!important; content:'${INSTANCE_NAME}'!important; white-space:var(--fp);margin:var(--f0);display:var(--fi);opacity:var(--fa);}"

case $INSTANCE_TYPE in
mastodon) TEMPLATE=$MASTODON_TEMPLATE ;;
pleroma) TEMPLATE=$PLEROMA_TEMPLATE ;;
gotosocial | gts) TEMPLATE=$GTS_TEMPLATE ;;
misskey) TEMPLATE=$MISSKEY_TEMPLATE ;;
akkoma) TEMPLATE=$AKKOMA_TEMPLATE ;;
friendica) TEMPLATE=$FRIENDICA_TEMPLATE ;;
esac

echo $TEMPLATE >>$CSS_FILE
git add $CSS_FILE
git commit -m "Added $INSTANCE_URL"
exit 0
